services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15-alpine
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5


  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    environment:
      - WORKER_CONCURRENCY=${WORKER_CONCURRENCY}
      - WORKER_POLL_INTERVAL=${WORKER_POLL_INTERVAL}
      - REDIS_URL=redis://redis:6379
    command: npm run worker
    networks:
      - backend
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy



  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - PORT=${PORT}
      - WORKER_CONCURRENCY=${WORKER_CONCURRENCY}
      - WORKER_POLL_INTERVAL=${WORKER_POLL_INTERVAL}
    networks:
      - backend
    command: npm run db:seed && npm run start
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
      worker:
        condition: service_started


volumes:
  postgres_data:
    driver: local

networks:
  backend:
    driver: bridge
